Cypress UI automated test cases of console
hyperledger-labs/fabric-operations-console pull request #537
Opened 2023-10-09 13:25 UTC by ketulsha

#### Type of change
Cypress UI automated test cases of console

#### Description
Cypress UI automated test cases of console and readme file to start

2023-10-10 01:12 UTC, dshuffma-ibm requested changes
this is really nice! i have a few thoughts:

- can we tie this to run automatically with github actions?
  - apollo's: https://github.com/hyperledger-labs/fabric-operations-console/blob/main/.github/workflows/apollo.yml

2023-10-10 01:15 UTC, dshuffma-ibm commented on packages/cypress/cypress/fixtures/test_data/Import/IBP_Import.zip
rename this to `Node_Import.zip`

2023-10-10 04:36 UTC, ketulsha commented on packages/cypress/cypress/fixtures/config.json
Yes, we need to provide console URL and login details in the config.json in "fixtures" folder so that automated test cases will run on that console URL. This is needed for local execution and Marvin pipeline both.

2023-10-10 05:02 UTC, ketulsha commented on packages/cypress/cypress/fixtures/test_data/Import/IBP_Import.zip
Done

2023-10-10 09:19 UTC, ketulsha commented
> this is really nice! i have a few thoughts:
> 
> * can we tie this to run automatically with github actions?
>   
>   * apollo's: https://github.com/hyperledger-labs/fabric-operations-console/blob/main/.github/workflows/apollo.yml

Added cypress.yml under workflows folder.

2023-10-10 18:08 UTC, dshuffma-ibm requested changes
there's a few hundred more files now? looks like you copied the whole app under the cypress folder... if this is just for github actions, can you remove all of these, and when github actions is running add a copy bash command to get the source data from `apollo/src` to where you want it.

2023-10-10 18:12 UTC, dshuffma-ibm commented on packages/cypress/cypress/fixtures/config.json
ok, your readme suggest editing this file so its just a template right?

can we set this file with more obvious dummy values, like:
```
{
    "loginUrl": "https://Your-Consoles-URL-Here",
    "loginUserName": "Username-Here",
    "loginDefaultPassword": "Password-Here",
    "loginPassword": "Password-Here"
}
```

2023-10-11 06:13 UTC, ketulsha commented on packages/cypress/cypress/fixtures/config.json
Updated the file with dummy values.

2023-10-12 14:31 UTC, ketulsha commented
@dshuffma-ibm - As per discussion, this PR is updated with new folder structure and ReadMe file that says Protractor is deprecated. 
Please review.Thanks!

2023-10-17 18:00 UTC, dshuffma-ibm commented on packages/apollo/test/cypress/package.json
hmmmm, i think i'll merge this regardless, but this file has a suspicious number of dependencies, we should only list the top level deps it takes to run this test. any dependencies of a dependency will automatically be tracked with the `package-lock.json` file and thus they do not (and should not) be listed in our `package.json` file.

sooo my ask is, can you strip down this list? starting on line 39?

2023-10-17 18:00 UTC, dshuffma-ibm commented on packages/cypress/cypress/fixtures/config.json
thanks

2023-10-17 18:01 UTC, dshuffma-ibm approved these changes

2023-10-17 18:04 UTC, dshuffma-ibm requested changes
ideally this will run automatically with our new builds, can you add a new github action test in the apollo file? https://github.com/hyperledger-labs/fabric-operations-console/blob/main/.github/workflows/apollo.yml#L12

2023-10-17 19:52 UTC, dshuffma-ibm commented on packages/apollo/test/cypress/package.json
@ketulsha

2023-10-17 19:54 UTC, merged